import { signal } from "@preact/signals-react";


export const chats = signal([
    {"role":"system","key":0,
        "content":'You are an assistant. You give brief and straightforward responses. You make your responses feel human, a bit jovial sometimes but mostly conscise'},
    // {'content':'HAHA something dey here number one \nsomeont sos sysd \ni go evn longer on this one to see whsaty will it now eclips eofr ogo and fif sodsf l s hlhlkl  khlkjkl  lklkjo  lkshjsl  slk slk dklfjs  ojslkjdi  dskfjoks fsdkfnl','key':1,'role':'user'},
    // {'content':'so adey go some','key':2,'role':'bot'},
    // {'content':'you see say we dey form','key':3,'role':'user'},
    // {'content':'a3 for life chale','key':4,'role':'bot'},        
    // {'content':'something dey here','key':5,'role':'user'},
    // {'content':'so adey go some','key':6,'role':'bot'},
    // {'content':'you see say we dey form','key':7,'role':'user'},
    // {'content':'a3 for life chale','key':8,'role':'bot'}, 
    // {'content':'something dey here','key':9,'role':'user'},
    // {'content':'so adey go some','key':10,'role':'bot'},
    // {'content':'you see say we dey form','key':11,'role':'user'},
    // {'content':'a3 for life chale','key':12,'role':'bot'}, 
    // {'content':'something dey here','key':13,'role':'user'},
    // {'content':'so adey go some','key':14,'role':'bot'},
    // {'content':'you see say we dey form','key':15,'role':'user'},
    // {'content':'a3 for life chale','key':16,'role':'bot'}, 
    // {'content':'something dey here','key':17,'role':'user'},
    // {'content':'so adey go some','key':18,'role':'bot'},
    // {'content':'you see say we dey form','key':19,'role':'user'},
    // {'content':'a3 for life chale','key':20,'role':'bot'},
    // {'content':'something dey here','key':21,'role':'user'},
    // {'content':'so adey go some','key':22,'role':'bot'},
    // {'content':'you see say we dey form','key':23,'role':'user'},
    // {'content':'a3 for life chale last','key':24,'role':'bot'},  
])


export const aigenimages = signal([
    {'prompt':'something dey here','key':1,'image':require('./assets/sk.jpg')},
    {'prompt':'so adey go some','key':2,'image':''},
    {'prompt':'you see say we dey form','key':3,'image':''},
    {'prompt':'a3 for life chale','key':4,'image':''},        
    {'prompt':'something dey here','key':5,'image':''},
    {'prompt':'so adey go some','key':6,'image':''},
    {'prompt':'you see say we dey form','key':7,'image':''},
    {'prompt':'a3 for life chale','key':8,'image':''}, 
    {'prompt':'something dey here','key':9,'image':''},
    {'prompt':'so adey go some','key':10,'image':''},
    {'prompt':'you see say we dey form','key':11,'image':''},
    {'prompt':'a3 for life chale','key':12,'image':''}, 
    {'prompt':'something dey here','key':13,'image':''},
    {'prompt':'so adey go some','key':14,'image':''},
    {'prompt':'you see say we dey form','key':15,'image':''},
    {'prompt':'a3 for life chale','key':16,'image':''}, 
    {'prompt':'something dey here','key':17,'image':''},
     {'prompt':'so adey go some','key':18,'image':''},
    {'prompt':'you see say we dey form','key':19,'image':''},
    {'prompt':'a3 for life chale','key':20,'image':''},
    {'prompt':'something dey here','key':21,'image':''},
    {'prompt':'so adey go some','key':22,'image':''},
    {'prompt':'you see say we dey form','key':23,'image':''},
    {'prompt':'a3 for life chale 66666  last bottom','key':24,'image':require('./assets/sk.jpg')},  
]);